INSERT INTO ITEMS VALUES (1, 'Chips', 10);
INSERT INTO ITEMS VALUES (2, 'Hide & Seek Biscuit', 35);
INSERT INTO ITEMS VALUES (3, 'Apple', 50);
INSERT INTO ITEMS VALUES (4, 'Banana', 5);
INSERT INTO ITEMS VALUES (5, 'lolipop', 2);
INSERT INTO ITEMS VALUES (6, 'icecream', 30);
INSERT INTO ITEMS VALUES (7, 'Biryani', 180);

